# configs/config.yaml

# ========================================
# 模型参数配置
# ========================================

model:
  # 嵌入维度
  embed_size: 64
  # 动态记忆维度（用于动态图网络）
  memory_dim: 64
  # 时间编码维度
  time_dim: 16
  # 激活函数，可选 'relu', 'leaky_relu', 'tanh', 'sigmoid' 等
  activation: leaky_relu
  # 是否使用生成对抗网络（GAN）模块
  use_gan: True
  # 是否使用自适应对比学习（Contrastive Learning）模块
  use_cl: Ture
  # 是否使用知识图谱融合模块
  use_kg: False
  # 图神经网络的层数
  num_layers: 2
  # 图注意力网络的头数（用于 GAT）
  n_heads: 4

# ========================================
# 训练参数配置
# ========================================

training:
  # 学习率
  lr: 0.001
  # 批次大小
  batch_size: 256
  # 训练轮数
  num_epochs: 20
  # Loss 权重配置
  loss_weights:
    # 自适应对比学习损失的权重
    cl_weight: 0.1
    # GAN 损失的权重
    gan_weight: 0.1

# ========================================
# 对比学习参数配置
# ========================================

contrastive_learning:
  # 温度参数，用于对比学习损失
  temperature: 0.5

# ========================================
# GAN 模块参数配置
# ========================================

gan:
  # 噪声维度（生成器的输入维度）
  noise_dim: 64
  # 隐藏层维度
  hidden_dim: 128
  # 隐藏层的层数
  num_layers: 2
  # 激活函数
  activation: leaky_relu

# ========================================
# 数据路径配置
# ========================================

data:
  # 数据集根目录
  root_dir: 'data'
  # 训练集目录
  train_dir: 'data/train'
  # 验证集目录
  valid_dir: 'data/valid'
  # 测试集目录
  test_dir: 'data/test'

# ========================================
# 日志和模型保存配置
# ========================================

# configs/config.yaml

logging:
  log_dir: 'logs'
  log_filename: 'training.log'
  log_level: 'INFO'
  save_dir: 'saved_models'
  save_best_model: True

# ========================================
# 设备配置
# ========================================

device:
  # 设备类型，可选 'cpu', 'cuda'
  type: 'cuda'
  # 指定使用的 GPU 编号（如果有多块 GPU）
  gpu_id: 0

# ========================================
# 其他配置
# ========================================

other:
  # 随机种子
  seed: 42